var express = require('express');
var router = express.Router();
var Promise = require("bluebird");
var request = Promise.promisify(require("request"));
var _ = require('lodash');
var hbs = require('hbs');
var moment = require('moment');
var tz = require('moment-timezone');

var leaderboard = function(url) {

  function isInt(n) {
     return n % 1 === 0;
  }

  return new Promise(function(resolve, reject) {
    request(url, function callback(error, response, body) {
      if(!error && response.statusCode === 200){
        var leaderboard = JSON.parse(body);
        var rows = leaderboard.length/3;
        var data = [];
        var counter = 0;

        // add one extra row if needd
        if (!isInt(rows))
          rows = Math.floor(rows) + 1;

        for (var i=0;i<rows;i++) {
          var row = [];
          if (leaderboard[counter]) row.push(leaderboard[counter]);
          counter++;
          if (leaderboard[counter]) row.push(leaderboard[counter]);
          counter++;
          if (leaderboard[counter]) row.push(leaderboard[counter]);
          counter++;
          data.push(row)
        }
        resolve(data);
      }else{
        reject(error)
      }
    });
  });
};

function date_Sort(recordA,recordB){
  var diff =  new Date(recordA._source.sortDate).getTime() - new  Date(recordB._source.sortDate).getTime();
  return diff *  -1;
}
var developmentChallengesData = [
  {
    "Billing_Account_Name": "SiBM - Agile VR 2",
    "Topcoder_Project_Name": "SiBM - Agile VR 2",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 260,
    "Fee_Currency": "USD",
    "Fee": 130,
    "Duration": 0,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052127?type=Develop&lc=_HL_30052127_HL__blank_HL_",
    "Title": "SiBM - Agile VR 2 - VoIP - socket server F2F",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9271,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM Gamification Onboarding",
    "Topcoder_Project_Name": "IBM - SiBM - Gamification Onboarding App",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 252,
    "Fee_Currency": "USD",
    "Fee": 126,
    "Duration": 1,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051389?type=Develop&lc=_HL_30051389_HL__blank_HL_",
    "Title": "IBM - SiBM Support Easy Onboarding - talk configuration and certificate generation and email",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8965,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 300,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 358,
    "Fee_Currency": "USD",
    "Fee": 179,
    "Duration": 1,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052105?type=Develop&lc=_HL_30052105_HL__blank_HL_",
    "Title": "SiBM - Agile Standup Bug Fixes",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 150,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 199,
    "Fee_Currency": "USD",
    "Fee": 99.5,
    "Duration": 1,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051830?type=Develop&lc=_HL_30051830_HL__blank_HL_",
    "Title": "SiBM - ClipStreamer User Guide",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - IBM Help Desk",
    "Topcoder_Project_Name": "SiBM - IBM@HD",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 276,
    "Fee_Currency": "USD",
    "Fee": 138,
    "Duration": 2,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051566?type=Develop&lc=_HL_30051566_HL__blank_HL_",
    "Title": "IBM at HD Mobile App User Guide",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9038,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 260,
    "Fee_Currency": "USD",
    "Fee": 130,
    "Duration": 2,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052043?type=Develop&lc=_HL_30052043_HL__blank_HL_",
    "Title": "IBM SiBM BlueView Interview Technical Document",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Agile VR 2",
    "Topcoder_Project_Name": "SiBM - Agile VR 2",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 300,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 382,
    "Fee_Currency": "USD",
    "Fee": 0,
    "Duration": 2,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052128?type=Develop&lc=_HL_30052128_HL__blank_HL_",
    "Title": "SiBM - Agile VR 2 - VoIP - Unity3d F2F",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9271,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 260,
    "Fee_Currency": "USD",
    "Fee": 130,
    "Duration": 2,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052415?type=Develop&lc=_HL_30052415_HL__blank_HL_",
    "Title": "SiBM - ClipStreamer Change Login to SSO",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - IBM Help Desk",
    "Topcoder_Project_Name": "SiBM - IBM@HD",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 100,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 146,
    "Fee_Currency": "USD",
    "Fee": 73,
    "Duration": 2,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051797?type=Develop&lc=_HL_30051797_HL__blank_HL_",
    "Title": "Hybrid Mobile App Update - Change Home Button to Back Button",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9038,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM Gamification Onboarding",
    "Topcoder_Project_Name": "IBM - SiBM - Gamification Onboarding App",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 400,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 772,
    "Fee_Currency": "USD",
    "Fee": 386,
    "Duration": 3,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051244?type=Develop&lc=_HL_30051244_HL__blank_HL_",
    "Title": "IBM - SiBM Support Easy OnBoarding backend service",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8965,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 345,
    "Fee_Currency": "USD",
    "Fee": 172.5,
    "Duration": 3,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051440?type=Develop&lc=_HL_30051440_HL__blank_HL_",
    "Title": "(F2F) IBM - SiBM - Travel Companion Mobile App UI Prototype Update Challenge",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 450,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 589,
    "Fee_Currency": "USD",
    "Fee": 294.5,
    "Duration": 3,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051703?type=Develop&lc=_HL_30051703_HL__blank_HL_",
    "Title": "IBM - SiBM Blueview Interview Helper Tablet F2F UI Prototype Challenge",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 400,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 724,
    "Fee_Currency": "USD",
    "Fee": 362,
    "Duration": 4,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051315?type=Develop&lc=_HL_30051315_HL__blank_HL_",
    "Title": "IBM SiBM Internet of Things Assessment Back-end Services",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - YouMix",
    "Topcoder_Project_Name": "SiBM - YouMix",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 260,
    "Fee_Currency": "USD",
    "Fee": 130,
    "Duration": 4,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052383?type=Develop&lc=_HL_30052383_HL__blank_HL_",
    "Title": "IBM - SiBM YouMix Slack Integration",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9256,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 355,
    "Fee_Currency": "USD",
    "Fee": 177.5,
    "Duration": 5,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051377?type=Develop&lc=_HL_30051377_HL__blank_HL_",
    "Title": "$250 SiBM - Internet of Things Assessment UI Prototype Updates (AngularJS/HTML/CSS/JS)",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - IBM Help Desk",
    "Topcoder_Project_Name": "SiBM - IBM@HD",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 100,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 174,
    "Fee_Currency": "USD",
    "Fee": 87,
    "Duration": 5,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051934?type=Develop&lc=_HL_30051934_HL__blank_HL_",
    "Title": "SiBM - IBM(at)HD Replace Google Map API",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9038,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 300,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 478,
    "Fee_Currency": "USD",
    "Fee": 239,
    "Duration": 5,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052108?type=Develop&lc=_HL_30052108_HL__blank_HL_",
    "Title": "SiBM - Blueview Interview - create interviewer - F2F",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM Gamification Onboarding",
    "Topcoder_Project_Name": "SiBM - Gamification Onboarding - Part 2",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 800,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2988,
    "Fee_Currency": "USD",
    "Fee": 1494,
    "Duration": 5,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052424?type=Develop&lc=_HL_30052424_HL__blank_HL_",
    "Title": "[Good Bonus Offered] Gamification Onboarding Integration",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9289,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 150,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 205,
    "Fee_Currency": "USD",
    "Fee": 102.5,
    "Duration": 5,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052392?type=Develop&lc=_HL_30052392_HL__blank_HL_",
    "Title": "SiBM - BlueView Interview - SSO F2F",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 305,
    "Fee_Currency": "USD",
    "Fee": 152.5,
    "Duration": 5,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052418?type=Develop&lc=_HL_30052418_HL__blank_HL_",
    "Title": "SiBM - Travel Companion Tech Documentation",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 536,
    "Fee_Currency": "USD",
    "Fee": 268,
    "Duration": 6,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051441?type=Develop&lc=_HL_30051441_HL__blank_HL_",
    "Title": "IBM SiBM Internet of Things Assessment Back-end Services 2",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - IBM Help Desk",
    "Topcoder_Project_Name": "SiBM - IBM@HD",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 305,
    "Fee_Currency": "USD",
    "Fee": 152.5,
    "Duration": 6,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051875?type=Develop&lc=_HL_30051875_HL__blank_HL_",
    "Title": "SiBM - IBM(at)HD Tech Documentation",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9038,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 355,
    "Fee_Currency": "USD",
    "Fee": 177.5,
    "Duration": 6,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051831?type=Develop&lc=_HL_30051831_HL__blank_HL_",
    "Title": "SiBM - Agile Stand- Up User Guide",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - IBM Help Desk",
    "Topcoder_Project_Name": "SiBM - IBM@HD",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 276,
    "Fee_Currency": "USD",
    "Fee": 138,
    "Duration": 6,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051933?type=Develop&lc=_HL_30051933_HL__blank_HL_",
    "Title": "SiBM - IBM(at)HD Load Real Data",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9038,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 300,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 420,
    "Fee_Currency": "USD",
    "Fee": 210,
    "Duration": 6,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051943?type=Develop&lc=_HL_30051943_HL__blank_HL_",
    "Title": "(F2F) IBM - SiBM - ClipStreamer UI Prototype Updates",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - IBM Help Desk",
    "Topcoder_Project_Name": "SiBM - IBM@HD",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 350,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 495,
    "Fee_Currency": "USD",
    "Fee": 247.5,
    "Duration": 6,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051987?type=Develop&lc=_HL_30051987_HL__blank_HL_",
    "Title": "SiBM - IBM(at)HD Misc Bug Fixes",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9038,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Customer Spotlight",
    "Topcoder_Project_Name": "SiBM - Customer Spotlight",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 750,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 1630,
    "Fee_Currency": "USD",
    "Fee": 815,
    "Duration": 6,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052013?type=Develop&lc=_HL_30052013_HL__blank_HL_",
    "Title": "!!72hrs IBM - SiBM Customer Spotlight Back-end Services",
    "Type": "Code",
    "Topcoder_Project_Id": 9257,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - IBM Help Desk",
    "Topcoder_Project_Name": "SiBM - IBM@HD",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 750,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 1580,
    "Fee_Currency": "USD",
    "Fee": 790,
    "Duration": 7,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051296?type=Develop&lc=_HL_30051296_HL__blank_HL_",
    "Title": "IBM - SiBM IBM(at)HD Backend Service",
    "Type": "Code",
    "Topcoder_Project_Id": 9038,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 600,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 1184,
    "Fee_Currency": "USD",
    "Fee": 592,
    "Duration": 7,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051055?type=Develop&lc=_HL_30051055_HL__blank_HL_",
    "Title": "IBM SiBM - ClipStreamer Browser Bookmarklet POC",
    "Type": "Code",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Event Connect (Mathers)",
    "Topcoder_Project_Name": "IBM - ESS Social Network Integration",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2700,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 4308,
    "Fee_Currency": "USD",
    "Fee": 2154,
    "Duration": 7,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052042?type=Develop&lc=_HL_30052042_HL__blank_HL_",
    "Title": "SiBM - IBM Enterprise Social Network Integration 1",
    "Type": "Code",
    "Topcoder_Project_Id": 9295,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 252,
    "Fee_Currency": "USD",
    "Fee": 126,
    "Duration": 7,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052044?type=Develop&lc=_HL_30052044_HL__blank_HL_",
    "Title": "IBM SiBM Internet of Things Assessment Technical Document",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 252,
    "Fee_Currency": "USD",
    "Fee": 126,
    "Duration": 7,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052101?type=Develop&lc=_HL_30052101_HL__blank_HL_",
    "Title": "IBM SiBM BlueView Interview User Guide",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Watson Ecosystem - 2015",
    "Topcoder_Project_Name": "Watson Pattern Explorer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2068,
    "Fee_Currency": "USD",
    "Fee": 1034,
    "Duration": 7,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051167?type=Develop&lc=_HL_30051167_HL__blank_HL_",
    "Title": "Watson Pattern Explorer Custom Node RED Nodes",
    "Type": "Code",
    "Topcoder_Project_Id": 9068,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2168,
    "Fee_Currency": "USD",
    "Fee": 1084,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051554?type=Develop&lc=_HL_30051554_HL__blank_HL_",
    "Title": "IBM SiBM - ClipStreamer Mobile Share POC",
    "Type": "Code",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM Gamification Onboarding",
    "Topcoder_Project_Name": "IBM - SiBM - Gamification Onboarding App",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2400,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2876,
    "Fee_Currency": "USD",
    "Fee": 1438,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051044?type=Develop&lc=_HL_30051044_HL__blank_HL_",
    "Title": "IBM - SiBM Support Easy Onboarding Backend Integration Part 1",
    "Type": "Code",
    "Topcoder_Project_Id": 8965,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Watson Ecosystem - 2015",
    "Topcoder_Project_Name": "Watson Pattern Explorer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3840,
    "Fee_Currency": "USD",
    "Fee": 1920,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051169?type=Develop&lc=_HL_30051169_HL__blank_HL_",
    "Title": "IBM - SiBM Watson Pattern Explorer User Interface",
    "Type": "Code",
    "Topcoder_Project_Id": 9068,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Watson Ecosystem - 2015",
    "Topcoder_Project_Name": "Watson Pattern Explorer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2940,
    "Fee_Currency": "USD",
    "Fee": 1470,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051446?type=Develop&lc=_HL_30051446_HL__blank_HL_",
    "Title": "IBM - SiBM Watson Pattern Explorer - Flow Configuration POC",
    "Type": "Code",
    "Topcoder_Project_Id": 9068,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1800,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2352,
    "Fee_Currency": "USD",
    "Fee": 1176,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051956?type=Develop&lc=_HL_30051956_HL__blank_HL_",
    "Title": "IBM - SiBM Travel Companion Integration - Part 1 - Search Screen",
    "Type": "Code",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Watson Ecosystem - 2015",
    "Topcoder_Project_Name": "Watson Pattern Explorer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3840,
    "Fee_Currency": "USD",
    "Fee": 1920,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051168?type=Develop&lc=_HL_30051168_HL__blank_HL_",
    "Title": "Watson Pattern Explorer Node RED Flow",
    "Type": "Code",
    "Topcoder_Project_Id": 9068,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 292,
    "Fee_Currency": "USD",
    "Fee": 146,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052290?type=Develop&lc=_HL_30052290_HL__blank_HL_",
    "Title": "SiBM - ClipStreamer Tech Doc",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 500,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 650,
    "Fee_Currency": "USD",
    "Fee": 325,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052324?type=Develop&lc=_HL_30052324_HL__blank_HL_",
    "Title": "SiBM - ClipStreamer Bug Fixes",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Agile VR 2",
    "Topcoder_Project_Name": "SiBM - Agile VR 2",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2328,
    "Fee_Currency": "USD",
    "Fee": 1164,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052134?type=Develop&lc=_HL_30052134_HL__blank_HL_",
    "Title": "SiBM - Agile VR 2 - Bluemix Hosted Config and Video",
    "Type": "Code",
    "Topcoder_Project_Id": 9271,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Agile VR 2",
    "Topcoder_Project_Name": "SiBM - Agile VR 2",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1800,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2952,
    "Fee_Currency": "USD",
    "Fee": 1476,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052377?type=Develop&lc=_HL_30052377_HL__blank_HL_",
    "Title": "SiBM - Agile VR 2 - VoIP - Voice Chatting PoC",
    "Type": "Code",
    "Topcoder_Project_Id": 9271,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 305,
    "Fee_Currency": "USD",
    "Fee": 152.5,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051837?type=Develop&lc=_HL_30051837_HL__blank_HL_",
    "Title": "IBM - SiBM - Travel Companion Mobile App User Guide",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - IBM Help Desk",
    "Topcoder_Project_Name": "SiBM - IBM@HD",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1650,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2756,
    "Fee_Currency": "USD",
    "Fee": 1378,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051471?type=Develop&lc=_HL_30051471_HL__blank_HL_",
    "Title": "IBM - SiBM IBM(at)HD Front End Integration",
    "Type": "Code",
    "Topcoder_Project_Id": 9038,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "IBM - Watson Service Demos",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 3000,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 4820,
    "Fee_Currency": "USD",
    "Fee": 2410,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050897?type=Develop&lc=_HL_30050897_HL__blank_HL_",
    "Title": "IBM - SiBM Watson Tradeoff Analytics Service Mobile Demo",
    "Type": "Code",
    "Topcoder_Project_Id": 8958,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1800,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2232,
    "Fee_Currency": "USD",
    "Fee": 1116,
    "Duration": 9,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051054?type=Develop&lc=_HL_30051054_HL__blank_HL_",
    "Title": "IBM SiBM - ClipStreamer REST API",
    "Type": "Code",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3540,
    "Fee_Currency": "USD",
    "Fee": 1770,
    "Duration": 9,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051907?type=Develop&lc=_HL_30051907_HL__blank_HL_",
    "Title": "IBM SiBM BlueView Interview Interviewer Integration",
    "Type": "Code",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1500,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 1960,
    "Fee_Currency": "USD",
    "Fee": 980,
    "Duration": 9,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051928?type=Develop&lc=_HL_30051928_HL__blank_HL_",
    "Title": "IBM SiBM Internet of Things Assessment Integration Part 2",
    "Type": "Code",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM-CredentialsMe",
    "Topcoder_Project_Name": "SiBM-CredentialME",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1800,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2232,
    "Fee_Currency": "USD",
    "Fee": 1116,
    "Duration": 9,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051995?type=Develop&lc=_HL_30051995_HL__blank_HL_",
    "Title": "IBM - SiBM CredentialME Backend Service",
    "Type": "Code",
    "Topcoder_Project_Id": 9237,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 300,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 618,
    "Fee_Currency": "USD",
    "Fee": 309,
    "Duration": 9,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052326?type=Develop&lc=_HL_30052326_HL__blank_HL_",
    "Title": "SiBM - Blueview Interview - infinite scroll - F2F",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM -  DES Web Specialists",
    "Topcoder_Project_Name": "SiBM - DES Web Specialists",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1800,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2232,
    "Fee_Currency": "USD",
    "Fee": 1116,
    "Duration": 9,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052022?type=Develop&lc=_HL_30052022_HL__blank_HL_",
    "Title": "IBM - SiBM DES Web Specialists Back-end Services",
    "Type": "Code",
    "Topcoder_Project_Id": 9258,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Agile VR 2",
    "Topcoder_Project_Name": "SiBM - Agile VR 2",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2640,
    "Fee_Currency": "USD",
    "Fee": 1320,
    "Duration": 9,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052132?type=Develop&lc=_HL_30052132_HL__blank_HL_",
    "Title": "SiBM - Agile VR 2 - Mural - Post-it Wall",
    "Type": "Code",
    "Topcoder_Project_Id": 9271,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "IBM - Watson Service Demos",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2700,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 4348,
    "Fee_Currency": "USD",
    "Fee": 2174,
    "Duration": 9,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050894?type=Develop&lc=_HL_30050894_HL__blank_HL_",
    "Title": "IBM - SiBM Watson Speech Translator Services Mobile Demo",
    "Type": "Code",
    "Topcoder_Project_Id": 8958,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "IBM - Watson Service Demos",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 4635,
    "Fee_Currency": "USD",
    "Fee": 2317.5,
    "Duration": 9,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051073?type=Develop&lc=_HL_30051073_HL__blank_HL_",
    "Title": "IBM - SiBM Watson Alchemy Vision Face Tagging Service Mobile Demo",
    "Type": "Code",
    "Topcoder_Project_Id": 8958,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2700,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3408,
    "Fee_Currency": "USD",
    "Fee": 1704,
    "Duration": 10,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051112?type=Develop&lc=_HL_30051112_HL__blank_HL_",
    "Title": "IBM SiBM BlueView Interview HR Integration",
    "Type": "Code",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM Gamification Onboarding",
    "Topcoder_Project_Name": "IBM - SiBM - Gamification Onboarding App",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 275,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 331.5,
    "Fee_Currency": "USD",
    "Fee": 165.75,
    "Duration": 10,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051547?type=Develop&lc=_HL_30051547_HL__blank_HL_",
    "Title": "IBM - SiBM Support Easy OnBoarding UI Prototype F2F Challenge",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8965,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2248,
    "Fee_Currency": "USD",
    "Fee": 1124,
    "Duration": 10,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051111?type=Develop&lc=_HL_30051111_HL__blank_HL_",
    "Title": "IBM SiBM BlueView Interview Back-end Services",
    "Type": "Code",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1800,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3072,
    "Fee_Currency": "USD",
    "Fee": 1536,
    "Duration": 10,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051096?type=Develop&lc=_HL_30051096_HL__blank_HL_",
    "Title": "IBM SiBM Agile Stand-up Back-end Services",
    "Type": "Code",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - YouMix",
    "Topcoder_Project_Name": "SiBM - YouMix",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1500,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2660,
    "Fee_Currency": "USD",
    "Fee": 1330,
    "Duration": 10,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052005?type=Develop&lc=_HL_30052005_HL__blank_HL_",
    "Title": "IBM - SiBM YouMix Back-end Services",
    "Type": "Code",
    "Topcoder_Project_Id": 9256,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM-CredentialsMe",
    "Topcoder_Project_Name": "SiBM-CredentialME",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2504,
    "Fee_Currency": "USD",
    "Fee": 1252,
    "Duration": 10,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051998?type=Develop&lc=_HL_30051998_HL__blank_HL_",
    "Title": "IBM - SiBM CredentialME Front End Integration 1",
    "Type": "Code",
    "Topcoder_Project_Id": 9237,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 2640,
    "Fee_Currency": "USD",
    "Fee": 1320,
    "Duration": 11,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052201?type=Develop&lc=_HL_30052201_HL__blank_HL_",
    "Title": "IBM - SiBM Travel Companion Integration - Restaurant Addition and hybrid mobile app",
    "Type": "Code",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 600,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 0,
    "Fee_Currency": "USD",
    "Fee": 0,
    "Duration": 11,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052359?type=Develop&lc=_HL_30052359_HL__blank_HL_",
    "Title": "IBM SiBM Internet of Things Assessment Integration F2F",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1650,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3157,
    "Fee_Currency": "USD",
    "Fee": 1578.5,
    "Duration": 12,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051434?type=Develop&lc=_HL_30051434_HL__blank_HL_",
    "Title": "IBM - SiBM Blueview Interview Helper Tablet UI Prototype Challenge - Part 2",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 325,
    "Fee_Currency": "USD",
    "Fee": 162.5,
    "Duration": 12,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051921?type=Develop&lc=_HL_30051921_HL__blank_HL_",
    "Title": "SiBM - Agile Stand- Up Tech Documentation",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 400,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 464,
    "Fee_Currency": "USD",
    "Fee": 232,
    "Duration": 12,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052239?type=Develop&lc=_HL_30052239_HL__blank_HL_",
    "Title": "SiBM - Agile Standup Bug Fixes",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM Gamification Onboarding",
    "Topcoder_Project_Name": "IBM - SiBM - Gamification Onboarding App",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1950,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3775.32,
    "Fee_Currency": "USD",
    "Fee": 1887.66,
    "Duration": 13,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051233?type=Develop&lc=_HL_30051233_HL__blank_HL_",
    "Title": "FAST!! 72Hours - IBM - SiBM Support Easy OnBoarding UI Prototype Challenge Part 2",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 8965,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3502,
    "Fee_Currency": "USD",
    "Fee": 1751,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050959?type=Develop&lc=_HL_30050959_HL__blank_HL_",
    "Title": "IBM - SiBM Internet of Things Assessment Mobile App UI Prototype Challenge",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2700,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 4566,
    "Fee_Currency": "USD",
    "Fee": 2283,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051212?type=Develop&lc=_HL_30051212_HL__blank_HL_",
    "Title": "IBM - SiBM Blueview Interview Helper Tablet UI Prototype Challenge - Part 1",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 700,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 1530,
    "Fee_Currency": "USD",
    "Fee": 765,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051293?type=Develop&lc=_HL_30051293_HL__blank_HL_",
    "Title": "IBM - SiBM Travel Companion Backend Service",
    "Type": "Code",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM-CredentialsMe",
    "Topcoder_Project_Name": "SiBM-CredentialME",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2400,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 4772,
    "Fee_Currency": "USD",
    "Fee": 2386,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051994?type=Develop&lc=_HL_30051994_HL__blank_HL_",
    "Title": "IBM - SiBM CredentialME UI Prototype Challenge",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 9237,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - YouMix",
    "Topcoder_Project_Name": "SiBM - YouMix",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2700,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3486,
    "Fee_Currency": "USD",
    "Fee": 1743,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052004?type=Develop&lc=_HL_30052004_HL__blank_HL_",
    "Title": "IBM - SiBM YouMix Prototype",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 9256,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3992,
    "Fee_Currency": "USD",
    "Fee": 1996,
    "Duration": 15,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051208?type=Develop&lc=_HL_30051208_HL__blank_HL_",
    "Title": "IBM SiBM - ClipStreamer Architecture Challenge",
    "Type": "Architecture",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1800,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3382.32,
    "Fee_Currency": "USD",
    "Fee": 1691.16,
    "Duration": 15,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051225?type=Develop&lc=_HL_30051225_HL__blank_HL_",
    "Title": "IBM - SiBM Agile StandUp Tool UI Prototype Challenge",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3782,
    "Fee_Currency": "USD",
    "Fee": 1891,
    "Duration": 15,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051565?type=Develop&lc=_HL_30051565_HL__blank_HL_",
    "Title": "IBM SiBM Agile Standup Integration Assembly",
    "Type": "Assembly Competition",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - IBM Help Desk",
    "Topcoder_Project_Name": "SiBM - IBM@HD",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2400,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 5652,
    "Fee_Currency": "USD",
    "Fee": 2826,
    "Duration": 16,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051221?type=Develop&lc=_HL_30051221_HL__blank_HL_",
    "Title": "IBM - SiBM -  IBM(at)HD Mobile UI Prototype Challenge",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 9038,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3782,
    "Fee_Currency": "USD",
    "Fee": 1891,
    "Duration": 16,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051773?type=Develop&lc=_HL_30051773_HL__blank_HL_",
    "Title": "IBM SiBM Agile Standup Web Socket Integration Assembly",
    "Type": "Assembly Competition",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2400,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3700,
    "Fee_Currency": "USD",
    "Fee": 1850,
    "Duration": 18,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051052?type=Develop&lc=_HL_30051052_HL__blank_HL_",
    "Title": "IBM - SiBM - ClipStreamer Responsive UI Prototype Challenge",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "IBM - Mood Marbles",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 4860,
    "Fee_Currency": "USD",
    "Fee": 2430,
    "Duration": 18,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050666?type=Develop&lc=_HL_30050666_HL__blank_HL_",
    "Title": "IBM - SiBM - Mood Marbles Mobile Prototype UI Challenge",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 8927,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2550,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3080,
    "Fee_Currency": "USD",
    "Fee": 1540,
    "Duration": 19,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052072?type=Develop&lc=_HL_30052072_HL__blank_HL_",
    "Title": "IBM SiBM - ClipStreamer Web Integration Assembly",
    "Type": "Assembly Competition",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM Gamification Onboarding",
    "Topcoder_Project_Name": "IBM - SiBM - Gamification Onboarding App",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 4460.58,
    "Fee_Currency": "USD",
    "Fee": 2230.29,
    "Duration": 20,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051231?type=Develop&lc=_HL_30051231_HL__blank_HL_",
    "Title": "IBM - SiBM Support Easy OnBoarding UI Prototype Challenge - Part 1",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 8965,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2700,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 3048,
    "Fee_Currency": "USD",
    "Fee": 1524,
    "Duration": 20,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051109?type=Develop&lc=_HL_30051109_HL__blank_HL_",
    "Title": "IBM SiBM Internet of Things Assessment Mobile Integration",
    "Type": "Code",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2700,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 4416,
    "Fee_Currency": "USD",
    "Fee": 2208,
    "Duration": 20,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050998?type=Develop&lc=_HL_30050998_HL__blank_HL_",
    "Title": "IBM - SiBM - Travel Companion Mobile App UI Prototype Challenge",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 500,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 610,
    "Fee_Currency": "USD",
    "Fee": 305,
    "Duration": 20,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052475?type=Develop&lc=_HL_30052475_HL__blank_HL_",
    "Title": "IBM - SiBM Travel Companion - Hybride Mobile App - Bug fix",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM -  DES Web Specialists",
    "Topcoder_Project_Name": "SiBM - DES Web Specialists",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2700,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 4584,
    "Fee_Currency": "USD",
    "Fee": 2292,
    "Duration": 23,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052375?type=Develop&lc=_HL_30052375_HL__blank_HL_",
    "Title": "SiBM - DES Web Specialists Contact Responsive App Prototype Challenge",
    "Type": "UI Prototype Competition",
    "Topcoder_Project_Id": 9258,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM Gamification Onboarding",
    "Topcoder_Project_Name": "SiBM - Gamification Onboarding - Part 2",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 650,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 690,
    "Fee_Currency": "USD",
    "Fee": 345,
    "Duration": 24,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052160?type=Develop&lc=_HL_30052160_HL__blank_HL_",
    "Title": "IBM F2F - SiBM Support Easy OnBoarding Prototype Navigation Change Challenge",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9289,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 250,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 335,
    "Fee_Currency": "USD",
    "Fee": 167.5,
    "Duration": 25,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051946?type=Develop&lc=_HL_30051946_HL__blank_HL_",
    "Title": "SiBM - Agile Standup Change Login to SSO",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 100,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 0,
    "Fee_Currency": "USD",
    "Fee": 0,
    "Duration": 28,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052410?type=Develop&lc=_HL_30052410_HL__blank_HL_",
    "Title": "IBM SiBM Internet of Things PDF generation update F2F",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM-CredentialsMe",
    "Topcoder_Project_Name": "SiBM-CredentialME",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 300,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 370,
    "Fee_Currency": "USD",
    "Fee": 185,
    "Duration": 34,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052148?type=Develop&lc=_HL_30052148_HL__blank_HL_",
    "Title": "SiBM-CredentialMe - Mozilla Backpack PoC F2F",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 9237,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Develop",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 200,
    "Member_Payment_Total_Currency": "USD",
    "Member_Payment_Total": 252,
    "Fee_Currency": "USD",
    "Fee": 126,
    "Duration": 37,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051866?type=Develop&lc=_HL_30051866_HL__blank_HL_",
    "Title": "SiBM - Internet of Things Assessment Mobile App User Guide",
    "Type": "First2Finish",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  }
];
var designChallengesData = [
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 100,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 140,
    "Fee_Currency": "USD",
    "Fee": 70,
    "Duration": 3,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051234?type=Design&lc=_HL_30051234_HL__blank_HL_",
    "Title": "IBM - SiBM - Travel Companion Design Refinement F2F Challenge",
    "Type": "Design First2Finish",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 300,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 340,
    "Fee_Currency": "USD",
    "Fee": 170,
    "Duration": 3,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051457?type=Design&lc=_HL_30051457_HL__blank_HL_",
    "Title": "IBM - SiBM - ClipStreamer Responsive Application Design Updates F2F Challenge",
    "Type": "Design First2Finish",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Smart Ticketing",
    "Topcoder_Project_Name": "SiBM - Smart Ticketing",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 175,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 215,
    "Fee_Currency": "USD",
    "Fee": 107.5,
    "Duration": 3,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051685?type=Design&lc=_HL_30051685_HL__blank_HL_",
    "Title": "IBM - SiBM - Smart Ticketing Design Slice and Style Tile F2F Challenge",
    "Type": "Design First2Finish",
    "Topcoder_Project_Id": 9081,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Event Connect (Mathers)",
    "Topcoder_Project_Name": "IBM - Event Connect",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 3600,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 4375,
    "Fee_Currency": "USD",
    "Fee": 2187.5,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051833?type=Design&lc=_HL_30051833_HL__blank_HL_",
    "Title": "IBM - SiBM Event Connect Web App Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9236,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Event Connect (Mathers)",
    "Topcoder_Project_Name": "IBM - Event Connect",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 3600,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 4375,
    "Fee_Currency": "USD",
    "Fee": 2187.5,
    "Duration": 8,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051834?type=Design&lc=_HL_30051834_HL__blank_HL_",
    "Title": "IBM - SiBM Event Connect Mobile App Wireframe Challenge Swiftoberfest",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9236,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM -  DES Web Specialists",
    "Topcoder_Project_Name": "SiBM - DES Web Specialists",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2600,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3375,
    "Fee_Currency": "USD",
    "Fee": 1687.5,
    "Duration": 10,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052019?type=Design&lc=_HL_30052019_HL__blank_HL_",
    "Title": "SiBM - DES Web Specialists Contact List App Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9258,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM-CredentialsMe",
    "Topcoder_Project_Name": "SiBM-CredentialME",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2025,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2800,
    "Fee_Currency": "USD",
    "Fee": 1400,
    "Duration": 12,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051920?type=Design&lc=_HL_30051920_HL__blank_HL_",
    "Title": "IBM - SiBM CredentialME Wireframe Design Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9237,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM -  DES Web Specialists",
    "Topcoder_Project_Name": "SiBM - DES Web Specialists",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 3200,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3900,
    "Fee_Currency": "USD",
    "Fee": 1950,
    "Duration": 12,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052277?type=Design&lc=_HL_30052277_HL__blank_HL_",
    "Title": "SiBM - DES Web Specialists Contact List App Design Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 9258,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Quick Quack",
    "Topcoder_Project_Name": "SiBM - Quick Quack",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2125,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2725,
    "Fee_Currency": "USD",
    "Fee": 1362.5,
    "Duration": 12,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052311?type=Design&lc=_HL_30052311_HL__blank_HL_",
    "Title": "IBM - SiBM - Quick Quack! Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9311,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "Cognitive Catalyst",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2025,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2800,
    "Fee_Currency": "USD",
    "Fee": 1400,
    "Duration": 12,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052358?type=Design&lc=_HL_30052358_HL__blank_HL_",
    "Title": "IBM - SiBM Cognitive Catalyst Portal Wireframe Design Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9334,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2500,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3900,
    "Fee_Currency": "USD",
    "Fee": 1950,
    "Duration": 12,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050997?type=Design&lc=_HL_30050997_HL__blank_HL_",
    "Title": "IBM - SiBM - Travel Companion Mobile App Design Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3225,
    "Fee_Currency": "USD",
    "Fee": 1612.5,
    "Duration": 13,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051224?type=Design&lc=_HL_30051224_HL__blank_HL_",
    "Title": "IBM - SiBM Agile StandUp Tool Design Challenge",
    "Type": "Web Design",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Smart Ticketing",
    "Topcoder_Project_Name": "SiBM - Smart Ticketing",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2750,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3525,
    "Fee_Currency": "USD",
    "Fee": 1762.5,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051413?type=Design&lc=_HL_30051413_HL__blank_HL_",
    "Title": "IBM - SiBM - Smart Ticketing  Responsive Tool Design Challenge",
    "Type": "Web Design",
    "Topcoder_Project_Id": 9081,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3300,
    "Fee_Currency": "USD",
    "Fee": 1650,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050882?type=Design&lc=_HL_30050882_HL__blank_HL_",
    "Title": "IBM - SiBM Internet of Things Assessment Mobile App Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Memory Recog",
    "Topcoder_Project_Name": "SiBM - Memory Recog",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1625,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2100,
    "Fee_Currency": "USD",
    "Fee": 1050,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052284?type=Design&lc=_HL_30052284_HL__blank_HL_",
    "Title": "IBM - SiBM Memory Recognition Mobile App Design Enhancements Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 9082,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bluemix TopCoder Button Experience",
    "Topcoder_Project_Name": "SiBM - Bluemix TopCoder Button Experience",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1950,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3162.5,
    "Fee_Currency": "USD",
    "Fee": 1581.25,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051000?type=Design&lc=_HL_30051000_HL__blank_HL_",
    "Title": "IBM - SiBM Project Dashboard Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9012,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Internet of Things Assessment",
    "Topcoder_Project_Name": "SiBM - Internet of Things Assessment",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2500,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3900,
    "Fee_Currency": "USD",
    "Fee": 1950,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050957?type=Design&lc=_HL_30050957_HL__blank_HL_",
    "Title": "IBM - SiBM Internet of Things Assessment Mobile App Design Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 8992,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2025,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3231.25,
    "Fee_Currency": "USD",
    "Fee": 1615.63,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051049?type=Design&lc=_HL_30051049_HL__blank_HL_",
    "Title": "IBM - SiBM - ClipStreamer Application Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bluemix TopCoder Button Experience",
    "Topcoder_Project_Name": "SiBM - Bluemix TopCoder Button Experience",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1550,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2662.5,
    "Fee_Currency": "USD",
    "Fee": 1331.25,
    "Duration": 14,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051121?type=Design&lc=_HL_30051121_HL__blank_HL_",
    "Title": "IBM - SiBM Project Dashboard Design Concepts Challenge 1",
    "Type": "Web Design",
    "Topcoder_Project_Id": 9012,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM-CredentialsMe",
    "Topcoder_Project_Name": "SiBM-CredentialME",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2500,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3275,
    "Fee_Currency": "USD",
    "Fee": 1637.5,
    "Duration": 15,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051993?type=Design&lc=_HL_30051993_HL__blank_HL_",
    "Title": "IBM - SiBM CredentialME Mobile Screen Design Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 9237,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Customer Spotlight",
    "Topcoder_Project_Name": "SiBM - Customer Spotlight",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2250,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3025,
    "Fee_Currency": "USD",
    "Fee": 1512.5,
    "Duration": 15,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052011?type=Design&lc=_HL_30052011_HL__blank_HL_",
    "Title": "IBM - SiBM - Customer Spotlight Design Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 9257,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - IBM Help Desk",
    "Topcoder_Project_Name": "SiBM - IBM@HD",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2500,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3900,
    "Fee_Currency": "USD",
    "Fee": 1950,
    "Duration": 15,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051124?type=Design&lc=_HL_30051124_HL__blank_HL_",
    "Title": "IBM - SIBM IBM(at)HD Mobile App Design Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 9038,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- IBM Travel Companion",
    "Topcoder_Project_Name": "SiBM - IBM Travel Companion",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2250,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3487.5,
    "Fee_Currency": "USD",
    "Fee": 1743.75,
    "Duration": 16,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050895?type=Design&lc=_HL_30050895_HL__blank_HL_",
    "Title": "IBM - SiBM - Travel Companion Mobile App Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 8993,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - YouMix",
    "Topcoder_Project_Name": "SiBM - YouMix",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1850,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2550,
    "Fee_Currency": "USD",
    "Fee": 1275,
    "Duration": 16,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051992?type=Design&lc=_HL_30051992_HL__blank_HL_",
    "Title": "IBM - SiBM YouMix Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9256,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3300,
    "Fee_Currency": "USD",
    "Fee": 1650,
    "Duration": 16,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051010?type=Design&lc=_HL_30051010_HL__blank_HL_",
    "Title": "IBM - SiBM Blueview Interview Helper Mobile Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM Gamification Onboarding",
    "Topcoder_Project_Name": "IBM - SiBM - Gamification Onboarding App",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1250,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2337.5,
    "Fee_Currency": "USD",
    "Fee": 1168.75,
    "Duration": 16,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051142?type=Design&lc=_HL_30051142_HL__blank_HL_",
    "Title": "IBM - SiBM CATHY Avatar Creation Design Challenge",
    "Type": "Banners/Icons",
    "Topcoder_Project_Id": 8965,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM- Clip Streamer",
    "Topcoder_Project_Name": "SiBM - ClipStreamer",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2500,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3275,
    "Fee_Currency": "USD",
    "Fee": 1637.5,
    "Duration": 17,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051050?type=Design&lc=_HL_30051050_HL__blank_HL_",
    "Title": "IBM - SiBM - ClipStreamer Responsive Application Design Challenge",
    "Type": "Web Design",
    "Topcoder_Project_Id": 8994,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater - iFund IT Logo",
    "Topcoder_Project_Name": "Whitewater - iFundIT Logo",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1475,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2300,
    "Fee_Currency": "USD",
    "Fee": 1150,
    "Duration": 17,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052041?type=Design&lc=_HL_30052041_HL__blank_HL_",
    "Title": "IBM - SiBM - ifundIT Logo Design Challenge",
    "Type": "Logo Design",
    "Topcoder_Project_Id": 9266,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - BlueView Interview",
    "Topcoder_Project_Name": "SiBM - BlueView Interview",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2525,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3856.25,
    "Fee_Currency": "USD",
    "Fee": 1928.13,
    "Duration": 18,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051210?type=Design&lc=_HL_30051210_HL__blank_HL_",
    "Title": "IBM - SiBM Blueview Interview Helper Responsive Design Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 9000,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "IBM - Super Series App",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1650,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2837.5,
    "Fee_Currency": "USD",
    "Fee": 1418.75,
    "Duration": 19,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050588?type=Design&lc=_HL_30050588_HL__blank_HL_",
    "Title": "IBM - SiBM Super Series - Mobile Viewer Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 8952,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Customer Spotlight",
    "Topcoder_Project_Name": "SiBM - Customer Spotlight",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1825,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2600,
    "Fee_Currency": "USD",
    "Fee": 1300,
    "Duration": 19,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051991?type=Design&lc=_HL_30051991_HL__blank_HL_",
    "Title": "IBM - SiBM - Customer Spotlight Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9257,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Data Lake",
    "Topcoder_Project_Name": "Datalake Mobile",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3635,
    "Fee_Currency": "USD",
    "Fee": 1817.5,
    "Duration": 19,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051041?type=Design&lc=_HL_30051041_HL__blank_HL_",
    "Title": "IBM Data Lake Mobile Catalog Tool Design Concepts Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 8987,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Memory Recog",
    "Topcoder_Project_Name": "SiBM - Memory Recog",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2500,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3200,
    "Fee_Currency": "USD",
    "Fee": 1600,
    "Duration": 21,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051590?type=Design&lc=_HL_30051590_HL__blank_HL_",
    "Title": "IBM - SiBM Social Networking Game Mobile App Design Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 9082,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Quick Quack",
    "Topcoder_Project_Name": "SiBM - Quick Quack",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2500,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3275,
    "Fee_Currency": "USD",
    "Fee": 1637.5,
    "Duration": 21,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052428?type=Design&lc=_HL_30052428_HL__blank_HL_",
    "Title": "IBM - SiBM - Quick Quack! Responsive Design Challenge",
    "Type": "Web Design",
    "Topcoder_Project_Id": 9311,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Whitewater- Agile Stand Up",
    "Topcoder_Project_Name": "SiBM - Agile Stand- Up",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2000,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3275,
    "Fee_Currency": "USD",
    "Fee": 1637.5,
    "Duration": 21,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050941?type=Design&lc=_HL_30050941_HL__blank_HL_",
    "Title": "IBM - sIBM Agile StandUp Tool Wireframes Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 8984,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "IBM - Super Series App",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1875,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3118.75,
    "Fee_Currency": "USD",
    "Fee": 1559.38,
    "Duration": 22,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050587?type=Design&lc=_HL_30050587_HL__blank_HL_",
    "Title": "IBM - SiBM Super Series - Web Editor App Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 8952,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "IBM - SiBM - Gamification Onboarding App",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2100,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3400,
    "Fee_Currency": "USD",
    "Fee": 1700,
    "Duration": 22,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050608?type=Design&lc=_HL_30050608_HL__blank_HL_",
    "Title": "IBM - SiBM  Gamification Onboarding Wireframes Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 8965,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "IBM - SiBM - Gamification Onboarding App",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2450,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3762.5,
    "Fee_Currency": "USD",
    "Fee": 1881.25,
    "Duration": 22,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050609?type=Design&lc=_HL_30050609_HL__blank_HL_",
    "Title": "IBM - SiBM Support Easy OnBoarding Web Design Challenge",
    "Type": "Application Front-End Design",
    "Topcoder_Project_Id": 8965,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Watson Ecosystem - 2015",
    "Topcoder_Project_Name": "IBM - Watson Service Demos",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2075,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3218.75,
    "Fee_Currency": "USD",
    "Fee": 1609.38,
    "Duration": 24,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050618?type=Design&lc=_HL_30050618_HL__blank_HL_",
    "Title": "IBM - SiBM Watson Tradeoff Analytics Service Mobile Demo Design Concepts Challenge",
    "Type": "Application Front-End Design",
    "Topcoder_Project_Id": 8958,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Watson Ecosystem - 2015",
    "Topcoder_Project_Name": "IBM - Watson Service Demos",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2075,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3368.75,
    "Fee_Currency": "USD",
    "Fee": 1684.38,
    "Duration": 25,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050619?type=Design&lc=_HL_30050619_HL__blank_HL_",
    "Title": "IBM - SiBM Watson AlchemyVision Face Tagging Service Mobile Demo Design Concepts Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 8958,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "IBM - Mood Marbles",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2500,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3825,
    "Fee_Currency": "USD",
    "Fee": 1912.5,
    "Duration": 26,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050498?type=Design&lc=_HL_30050498_HL__blank_HL_",
    "Title": "IBM - SiBM - Mood Marbles Mobile Design Concepts Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 8927,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Memory Recog",
    "Topcoder_Project_Name": "SiBM - Memory Recog",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1850,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 2625,
    "Fee_Currency": "USD",
    "Fee": 1312.5,
    "Duration": 26,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30051424?type=Design&lc=_HL_30051424_HL__blank_HL_",
    "Title": "IBM - SiBM Social Networking Game Mobile App Wireframe Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 9082,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - YouMix",
    "Topcoder_Project_Name": "SiBM - YouMix",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 3000,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 0,
    "Fee_Currency": "USD",
    "Fee": 0,
    "Duration": 26,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052003?type=Design&lc=_HL_30052003_HL__blank_HL_",
    "Title": "IBM - SiBM YouMix Design Challenge",
    "Type": "Web Design",
    "Topcoder_Project_Id": 9256,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM - Memory Recog",
    "Topcoder_Project_Name": "SiBM - Memory Recog",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 1625,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 1950,
    "Fee_Currency": "USD",
    "Fee": 975,
    "Duration": 27,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052304?type=Design&lc=_HL_30052304_HL__blank_HL_",
    "Title": "IBM - SiBM Memory Recognition Mobile App Game Design Challenge",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 9082,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Bill Bodin - 2015",
    "Topcoder_Project_Name": "IBM - Super Series App",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2200,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3195,
    "Fee_Currency": "USD",
    "Fee": 1597.5,
    "Duration": 28,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050755?type=Design&lc=_HL_30050755_HL__blank_HL_",
    "Title": "IBM - SiBM Super Series - Web Editor App Design Concepts Challenge",
    "Type": "Web Design",
    "Topcoder_Project_Id": 8952,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Watson Ecosystem - 2015",
    "Topcoder_Project_Name": "IBM - Watson Service Demos",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2500,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3800,
    "Fee_Currency": "USD",
    "Fee": 1900,
    "Duration": 30,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050617?type=Design&lc=_HL_30050617_HL__blank_HL_",
    "Title": "IBM - SiBM Watson Speech Translator Services Mobile Demo Design Concepts Challenge",
    "Type": "Application Front-End Design",
    "Topcoder_Project_Id": 8958,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "Event Connect (Mathers)",
    "Topcoder_Project_Name": "IBM - Event Connect",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2750,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3525,
    "Fee_Currency": "USD",
    "Fee": 1762.5,
    "Duration": 33,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30052147?type=Design&lc=_HL_30052147_HL__blank_HL_",
    "Title": "IBM - SiBM Event Connect Attendees Mobile App Design Challenge Swiftoberfest",
    "Type": "Widget or Mobile Screen Design",
    "Topcoder_Project_Id": 9236,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM",
    "Topcoder_Project_Name": "IBM - SiBM  Corporate Recognition Tool",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2250,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3487.5,
    "Fee_Currency": "USD",
    "Fee": 1743.75,
    "Duration": 35,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050614?type=Design&lc=_HL_30050614_HL__blank_HL_",
    "Title": "IBM - SiBM Corporate Recognition Tool Wireframes Challenge",
    "Type": "Wireframes",
    "Topcoder_Project_Id": 8925,
    "Status": "Completed"
  },
  {
    "Billing_Account_Name": "SiBM",
    "Topcoder_Project_Name": "IBM - SiBM  Corporate Recognition Tool",
    "Track": "Design",
    "Total_Prize_Currency": "USD",
    "Total_Prize": 2450,
    "Member_Payment_Total Currency": "USD",
    "Member_Payment_Total": 3737.5,
    "Fee_Currency": "USD",
    "Fee": 1868.75,
    "Duration": 41,
    "Topcoder_Link": "_HL_ENCODED_https://www.topcoder.com/challenge-details/30050615?type=Design&lc=_HL_30050615_HL__blank_HL_",
    "Title": "IBM - SiBM Corporate Recognition Tool Design Challenge",
    "Type": "Application Front-End Design",
    "Topcoder_Project_Id": 8925,
    "Status": "Completed"
  }
];
var challenges = function(req, res, next) {

  var type = req.url.split('/')[1];

  if (type === 'development') {
    req.challenges = developmentChallengesData;
  }
  else {
    req.challenges = designChallengesData;
  }
  /*
  var endpoint = process.env.DESIGN_CHALLENGES_ENDPOINT;
  if (type === 'development')
    endpoint = process.env.DEVELOPMENT_CHALLENGES_ENDPOINT;
  //console.log(endpoint);
  request(endpoint, function (error, response, body) {
    if (!error && response.statusCode == 200) {
      var challenges = JSON.parse(body);
      _.forEach(challenges, function(c, key){
        console.log(c._source.currentStatus);
        c._source.platforms = c._source.platforms.join(', ');
        c._source.technologies = c._source.technologies.join(', ');
        c._source.sortDate = c._source.submissionEndDate; //date used for sorting the records
        c._source.submissionEndDate = moment.utc(c._source.submissionEndDate).tz('America/New_York').format('MMMM Do YYYY, h:mm:ss a');
        //c._source.totalPrize = _.reduce(c._source.prize, function(sum, el) {
        //  return sum + el
        //}, 0)
        c._source.isComplete =  c._source.currentStatus === 'Completed' ? true : false;
      });
      challenges.sort(date_Sort);
      req.challenges = challenges;
    } else {
      req.challenges = [];
    }
    */
    return next();
  }

router.get('/welcome', function (req, res) {
  res.render('welcome');
});

router.get('/signup', function (req, res) {
  res.render('signup');
});

router.get('/faqs', function (req, res) {
  res.render('faqs');
});

router.get('/sponsors', function (req, res) {
  res.render('sponsors');
});

router.get('/design/leaderboard', function (req, res) {
  var allLeaderboards = [];
  Promise.join(
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-design-june'),
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-design-july'),
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-design-august'),
	  leaderboard('http://tc-leaderboard.herokuapp.com/sibm-design-september'),
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-design-october'),
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-design-november'),
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-design-december')
  ).then(function(data) {
    allLeaderboards = data;
  }).catch(function(e) {
    console.log(e);
  }).finally(function(){
    // would have like to pass a single array but hbs was choking
    res.render('design-leaderboard', {
      month1: allLeaderboards[0],
      month2: allLeaderboards[1],
      month3: allLeaderboards[2],
	    month4: allLeaderboards[3],
      monthOct: allLeaderboards[4],
      monthNov: allLeaderboards[5],
      monthDec: allLeaderboards[6]
    });
  });
});

router.get('/development/leaderboard', function (req, res) {
  var allLeaderboards = [];
  Promise.join(
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-dev-june'),
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-dev-july'),
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-dev-august'),
	  leaderboard('http://tc-leaderboard.herokuapp.com/sibm-dev-september'),
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-dev-october'),
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-dev-november'),
    leaderboard('http://tc-leaderboard.herokuapp.com/sibm-dev-december')
  ).then(function(data) {
    allLeaderboards = data;
  }).catch(function(e) {
    console.log(e);
  }).finally(function(){
    // would have like to pass a single array but hbs was choking
    res.render('development-leaderboard', {
      month1: allLeaderboards[0],
      month2: allLeaderboards[1],
      month3: allLeaderboards[2],
	    month4: allLeaderboards[3],
      monthOct: allLeaderboards[4],
      monthNov: allLeaderboards[5],
      monthDec: allLeaderboards[6]
    });
  });
});

router.get('/challenges/fun', function (req, res) {
  var funChallengeID = getNextFunChallenge();
  var registrationChallengeID = getNextRegistrationChallenge();
 
  res.render('challenges-fun.hbs',
					{
						funChallengeId: funChallengeID,
						registerChallengeId: registrationChallengeID
					});
});


function getNextChallengeAsPerTime(arr){
  var len = arr.length - 1;
  var index = len;
  var currentTime = moment();
  
  for(index = len;index > -1;index --){
    var currentChallenge = arr[index];
    var challengeTime = moment(currentChallenge.startTime,moment.ISO_8601);
    if(currentTime.isAfter(challengeTime)) {
      break;
    }
  }
  return arr[index].challengeID;
}

function getNextRegistrationChallenge(){
  var allRegistrationChallenge = [
      {challengeID: '30051734',startTime:'2015-11-17T13:00:00-05:00'},
      {challengeID: '30051932',startTime:'2015-11-24T14:00:00-05:00'},
      {challengeID: '30052250',startTime:'2015-12-01T15:00:00-05:00'},
      {challengeID: '30052251',startTime:'2015-12-08T16:00:00-05:00'},
      {challengeID: '30052252',startTime:'2015-12-15T17:00:00-05:00'},
      {challengeID: '30052253',startTime:'2015-12-22T18:00:00-05:00'}];
   
      return getNextChallengeAsPerTime(allRegistrationChallenge);
}

function getNextFunChallenge(){
   var allFunChallenge = [
      {challengeID: '30052167',startTime:'2015-11-17T02:00:00-05:00'},
      {challengeID: '30052191',startTime:'2015-11-24T03:00:00-05:00'},
      {challengeID: '30052255',startTime:'2015-12-01T04:00:00-05:00'},
      {challengeID: '30052256',startTime:'2015-12-08T05:00:00-05:00'},
      {challengeID: '30052257',startTime:'2015-12-15T06:00:00-05:00'},
      {challengeID: '30052258',startTime:'2015-12-22T09:00:00-05:00'}];
      
      return getNextChallengeAsPerTime(allFunChallenge);
}

router.get('/codeblitz', function (req, res) {
  res.render('codeblitz.hbs');
});

router.get('/design/challenges', challenges, function (req, res) {
  res.render('design-challenges.hbs', {
    challenges: req.challenges
  });
});

router.get('/development/challenges', challenges, function (req, res) {
  res.render('development-challenges.hbs', {
    challenges: req.challenges
  });
});

router.get('/', function (req, res) {
  res.render('index');
});

module.exports = router;
